@startmindmap
* MIT - Learning Theory
** 对很多内容大胆的说“不”
*** Case  九牛二虎之力弄懂了一些问同学、问前辈一秒钟就能得到答案的问题，获得了“战胜自己”的成就感。其实这是浪费时间
*** How?  知道是什么，可以用来干嘛，什么时候会用到它就可以了
*** What? 真的要用到的时候再学，到时学习的效果完全不一样；绝大部分人来说，把时间花在拓宽知识广度而不是深度，是回报率更高的做法

** 项目导向，为了用而学
*** Case 为了克服饮用水里的细菌问题，去学习微生物学的知识
*** How? 给自己“设计一些有趣或有回报的任务”，让学习变成你完成这些任务的手段
*** Why？学习有了明确的目的，学这块知识就是为了解决这个问题。

** Embodied Learning 身体动起来
*** case 设计动作只要能让你get到学习的主题，能把动作跟学习内容联系起来就行。eg:楞次定律
*** How？设计一些与学习内容相关的身体动作，身体思维一起动，学习效果加倍。同时也可以与“戏剧学习法”一起使用
*** Why？思维（mental) 和身体（physical) 是互相关联的

** MultiMedia Theory 多感官刺激
*** case 看图片记忆单词，下载三维模型了解建筑机械
*** How？ 人由五种基本的感官（视觉、听觉、触觉、嗅觉、味觉），要尽量同时刺激多种感官，提高学习效果
*** Why？ 尽量调动多种感官，这样学的更投入，效果更好

** Working Memory 理论：拆分小片段，多次回忆，多次复述
*** case 上课的过程中，学习的过程中，“边学边总结”，“边学边复习”。
*** How？不要等到学的量超过了你的Working Memory容量再去回忆，想想番茄工作法
*** Why？迭代式地整理记忆，回忆、头脑中总结转述为主

** Experiential Learning体验式学习
*** case 譬如AR应用，没那么刻意去学习，不知不觉就会了
*** How？就像旅游的过程中，自然就会观察学习到异国他乡的风土人情
*** Why? 多感觉的沉浸式体验，效果更佳，但是体验源需精心制作

** 合作式学习，找人一起学
*** case 找一个跟你风格差异比较大的同学，两人互改
*** How？ 要主动发起合作式学习，其过程类似于创业找合伙人。通过网络物色伙伴
*** Why? 时刻观察对方的学习/工作方式，互帮互学



@endmindmap