@startmindmap
* GTD
** 1 Capture收集
*** 目的：清空大脑，减少做事压力，增加当下注意力
*** 做法：头脑风暴，想到就记，费神费脑更要记
*** 时机：anytime，anyplace，flexible
*** Tips：找个思绪的线头，利用联想拽线头

** 2 Clarify厘清
*** 目的：量化收集箱任务，判断可行性
*** 做法：遍历任务，增删查改，再breakdown细节；记录：时间 重点 关键信息
*** 时机：打开Inbox之后，准备整理任务之前
*** 原则：清空Inobx变成[可执行状态]，排除不可做和立马可完成的任务
** 3 Organize整理
*** 方式： 列表/文件夹
*** 目的： 列表是按照所属层次关系能找到任务
*** 原则： 列表太细不易执行，长久不用就弃用；有大到小细分列表，如无必要不细分列表
*** 方式： 标签
*** 目的： 标记任务执行context；可作为自动化的trigger
*** 做法： 标签根据类别分类，可以是 时间 低点 设备 经历 优先级 etc

** 4 Reflect回顾
*** 目的：保障系统的有效性，不堆积无效和不能处理的任务
*** 做法：当下回顾（打开列表扫一眼）和 周期回顾（日 周 月）
*** 原则：核心意义是“保证你任务系统的有效性”，「定期回顾任务」形式大于意义
*** 方式：通过Filter进行灵活的过滤

** 5 Engage执行
*** 目的：找到当下状态适合执行的任务
*** 做法：对任务再一次过滤（比如它完成的情境、它需要的精神状态、完成这件事的预估时间等等）
*** 原则：活在当下，找到当下环境/环境/精力的最佳匹配任务，然后做就行了

@endmindmap